# Generated by Django 5.0.1 on 2025-11-04 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción del Material/Servicio')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_construccion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Gasto de Construcción',
                'verbose_name_plural': 'Gastos de Construcción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GastoCrianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pollitos', 'Compra de Pollitos'), ('concentrado', 'Concentrado/Alimento'), ('vacunas', 'Vacunas'), ('medicamentos', 'Medicamentos'), ('vitaminas', 'Vitaminas/Suplementos'), ('agua', 'Agua'), ('electricidad', 'Electricidad'), ('limpieza', 'Productos de Limpieza'), ('mantenimiento', 'Mantenimiento Equipos'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo de Gasto')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Cantidad/Descripción')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_crianza', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Gasto de Crianza',
                'verbose_name_plural': 'Gastos de Crianza',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente/Comprador')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (docenas/cubetas)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
